baseurl         = "https://security10x.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "security10x"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Security10x"
  subtitle    = "Learn The Art of Hacking - Cyber Security, Linux, Windows"

  cover       = "uploads/header.png"
  description = "Learn The Art of Hacking - Cyber Security, Linux, Windows"
  metaDescription = "Learn The Art of Hacking - Cyber Security, Linux, Windows"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "security10x"
  fbName = "sec10x"
  linkedinName= "security10x"

  logo = "uploads/logo.png"

  author = "Bablu Kumar"
  authorAvatar = "uploads/bablu.png"
  authorLocation = "New Delhi, India"
  authorDescription = "He writes about Python, Cloud Computing and Linux. He is an open-source and cyber security enthusiast. His Twitter handle: @hacback17"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Security News"
  url = "/tags/Security10x News/"
  weight = 100

[[menu.main]]
  name = "Learn Linux"
  url = "/categories/system-adminstrator/"
  weight = 99

[[menu.main]]
  name = "Learn Hacking"
  url = "/categories/Learn Hacking/"
  weight = 98

[[menu.main]]
  name = "Contact us"
  url = "/contact"
  weight = 50